version: 2.1

GO_VERSION: &go_version '1.24.2'
GORELEASER_VERSION: &goreleaser_version 'v2.9.0'
GO_MOD_CACHE_KEY: &go_mod_cache_key 'go-mod-1'

orbs:
  go: circleci/go@3.0.2
  codecov: codecov/codecov@5.3.0
  docker: circleci/docker@2.8.2

jobs:
  build:
    executor:
      name: ubuntu-2204
      machine:
        image: ubuntu-2204:current
    resource_class: large
    steps:
      - checkout
      - go/install:
          version: *go_version
      - go/load-cache:
            key: *go_mod_cache_key
      - go/mod-download
      - go/save-cache:
            key: *go_mod_cache_key
      - run: make coverage
      - codecov/upload:
          file: /tmp/manifest-node-exporter-coverage/coverage-merged.out
      - run: rm coverage.html
      - go/install-goreleaser:
          version: *goreleaser_version
      - run: goreleaser release --snapshot --clean
      - run:
          name: move artifacts
          command: |
            mkdir -p /tmp/artifacts
            mv dist/manifest-node-exporter_*.tar.gz dist/manifest-node-exporter_*.txt /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

  docker:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: lifted/manifest-node-exporter
          tag: "latest,${CIRCLE_SHA1}"
      - docker/push:
          digest-path: /tmp/digest.txt
          image: lifted/manifest-node-exporter
          tag: "latest,${CIRCLE_SHA1}"
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

  security:
    executor:
      name: go/default
      tag: *go_version
    steps:
      - checkout
      - run: make govulncheck
  release:
    executor:
      name: go/default
      tag: *go_version
    resource_class: xlarge
    steps:
      - checkout
      - go/install-goreleaser:
          version: *goreleaser_version
      # Something is wrong with the go/goreleaser orb, so we have to do this manually
      - run:
          name: Releasing to GitHub
          command: |
            goreleaser check
            goreleaser release

workflows:
  main:
    jobs:
      - build
      - security
  docker:
    jobs:
      - docker:
          context:
            - DOCKER_CREDS
          filters:
            branches:
              only:
                - main
  release:
    jobs:
      - release:
          context:
            - GITHUB_CREDS
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^v?\d(\.\d){2}$/ # e.g. major, minor, patch (0.1.1)
                - /^v?\d(\.\d){2}(-[\w-]+(\.[\w-]+)?)$/ # prereleases (0.1.1-alpha.8)